# This file is documented at `src/config.rs`. Look there if you're looking to tweak it.

lib_rs_prelude = """\
    #![no_std]\n\
    #![allow(non_camel_case_types)]\n\
    #![allow(non_snake_case)]\n\
    #![allow(non_upper_case_globals)]\n\
    #![allow(clippy::missing_safety_doc)]\n\
    #![allow(clippy::useless_transmute)]\n\
    #![allow(clippy::too_many_arguments)]\n\
    #![allow(clippy::len_without_is_empty)]\n\
    \n\
"""

# clib, sysclib, kernel/debug all use va_list.
[[lists]]
files = [
    "psp2/kernel/clib.h",
    "psp2kern/kernel/sysclib.h",
    "psp2kern/kernel/debug.h",
    "psp2/paf/stdc.h"
]
allowlists = ["va_list"]

[[lists]]
files = ["psp2/rtc.h"]
# rtc uses time_t from time.h.
allowlists = ["time_t"]
# Some modules import only psp2/rtc.h expecting SceRtcTick to exist.
extra_lines = ["pub use crate::psp2common::kernel::rtc::SceRtcTick;"]

# SceIoDevInfo is actually defined in psp2common/kernel/iofilemgr.h, but it's
# included via transitive dependency only (psp2/io/devctl.h)
[[lists]]
files = ["psp2/compat.h"]
extra_lines = ["use crate::psp2common::kernel::iofilemgr::*;"]

[[lists]]
files = ["psp2/paf/misc.h"]
extra_lines = ["use crate::psp2::kernel::threadmgr::lw_mutex::*;"]

[[lists]]
files = ["psp2/vshbridge.h"]
extra_lines = ["use crate::psp2common::kernel::modulemgr::*;"]
